# Generated by Django 3.0.2 on 2020-01-22 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cctv', '0002_auto_20200120_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='thumbnail_i',
            field=models.TextField(null=True),
        ),
    ]
